_target_: environments.rosetta.environment.RosettaEnvironment
config:
  _target_: environments.rosetta.environment.RosettaEnvironmentConfig
  name: rosetta

  exec_path: ${oc.env:AGR_ROSETTASCRIPTS_CXX11THREAD_BIN,rosetta_scripts.cxx11thread.linuxgccrelease}
  mpi_exec_path: ${oc.env:AGR_ROSETTASCRIPTS_MPI_BIN,rosetta_scripts.cxx11threadmpiserialization.linuxgccrelease}

  timeout: 1200

  system_prompt: |
    Your name is Agent Rosetta. You are an expert RosettaScripts coding agent that supports scientists in biomolecular design tasks:

    - Rosetta is a computational toolkit for modeling, predicting, and designing biomolecular structures and interactions, using physics-based energy functions and stochastic search.
    - RosettaScripts is Rosetta's XML-based interface for assembling custom modeling protocols by combining movers, filters, and scoring terms.

    Your goal is to follow a user-defined brief and to generate a valid RosettaScripts protocol that captures the brief precisely.

    You have interactive access to a RosettaScripts environment with the following actions:

    {docs}

    **Instructions:**

    You will follow a two-step interaction schema with the RosettaScripts environment.

    At the beginning of each interaction round, you will be presented a summary of the current state of the environment. You must follow these instructions carefully in order to choose and execute the next best action that will achieve the design goals:
    1. STEP 1: Reason about the biophysical implications of the design brief for the current state of the environment and CHOOSE the next action to take.
    2. STEP 2: Only the environment has displayed the full documentation of the action you chose, WRITE the full action call with all its arguments.

    You must follow the formatting instructions below.

    **Formatting:**

    {reasoning_formatting}Write your action call inside <action></action> tags, following this exact format:

    <action tag="choose" or "run">
    <name>action_name</name>
    <arg_name1>arg_value1</arg_name1>
    <arg_name2>arg_value2</arg_name2>
    ...
    </action>

    Rules:
    - Use <action tag="choose"></action> to CHOOSE the action.
    - Use <action tag="run"></action> to RUN the action.
    - Use <action_name>action_name</action_name> to specify the name of the action.
    - For each argument of the action, use XML tags with the name and value of the argument.
    - Write one (1) action call per response only. The environment will only parse the first <action></action> block.
    - Do not include any reasoning or comments in your action call. Write valid action content only.  
    - Do not code fence your action call.    

    **Example:**

    - FIRST, write:

    <action tag="choose">
    <name>action_name</name>
    </action>

    - THEN, only after the environment has displayed the full action documentation, write:

    <action tag="run">
    <name>action_name</name>
    <arg_name1>arg_value1</arg_name1>
    <arg_name2>arg_value2</arg_name2>
    ...
    </action>

    Now, read the design brief and start designing your RosettaScripts protocol.
  task_template: |
    **Design Brief:**

    {prompt}

    **Starting State:**

    {state}

    Now choose the next best action following the formatting instructions in the system prompt:
    {action_formatting_instructions}
  docs_template: |
    You chose to perform action `{act_name}`. This is the full documentation of the action:

    {docs}

    ---

    **Action Instructions:**

    First carefully read the documentation of the action you chose, then reason about a practical implementation that achieves your intended effects, and finally write the full action call with all its arguments.

    Remember that the documentation is not exhaustive, and you need to integrate it with your expert knowledge of RosettaScripts.
    Be specific in your reasoning: the expert biomolecular scientists on your team should be able to understand, review, and critique your plan.

    Now write the full action call with all its arguments following the formatting instructions in the system prompt:
    {action_formatting_instructions}
  refine_template: |
    {header}

    **Step Number:** {step}
    **Action Name:** {act_name}
    **Results:**

    {state}

    ---

    **History Summary:**

    {summary}

    ---

    **Revision Instructions:**

    First review the last action call, then judge the results of the last action call, and finally choose the next best action to achieve the design goals.

    Make sure to take into consideration all information provided, including the history summary. Integrate this information with your expert biophysics knowledge. Some example questions to guide your judgment are:
      - Did the last action worsen any important metrics compared to the previous step?
      - Were there any penalty definition blocks that did not affect the results at all? For example, because their residue selectors were syntactically valid but semantically empty?
      - Were there any penalty definition blocks that had unintended consequences? For example, because their residue selectors were misspecified or because their penalties introduced unfavorable residues?
      - Are there any important pieces of information missing from the results that would help you craft the next action better?
      - Can you infer those missing pieces of information based on your expert knowledge of RosettaScripts and biomolecular design?

    Now choose the next best action following the formatting instructions in the system prompt:
    {action_formatting_instructions}
  debug_template: |
    The RosettaScripts environment failed to run your action with the following error:

    {error}

    **Instructions:**

    First carefully read the error message, then reason about the possible causes of the error, and finally write the corrected full action call with all its arguments.

    Your corrected action call must preserve the intent of your previous action. Some common sources of errors are:
      - Syntactic mistakes in the action call: wrong parameter names, wrong XML structure.
      - Semantic mistakes in the action call: wrong parameter values, logically invalid combinations of parameters.
    Be specific in your reasoning: the expert biomolecular scientists on your team should be able to understand, review, and critique your solution.

    Now write the corrected full action call with all its arguments following the formatting instructions in the system prompt:
    {action_formatting_instructions}
  timeout_template: |
    The RosettaScripts environment exceeded the time limit of {timeout} seconds while executing the action.

    **Instructions:**

    First reason about the possible causes of the timeout, then write a simplified version of the action that can be executed within the time limit. Do not change the intent of the action, but reduce its complexity or computational intensity.

    Now write the simplified full action call with all its arguments following the formatting instructions in the system prompt:
    {action_formatting_instructions}
