SCORE_FIELDS: list[str] = [
    "fa_atr",
    "fa_rep",
    "fa_sol",
    "fa_intra_sol_xover4",
    "lk_ball_wtd",
    "fa_intra_rep",
    "fa_elec",
    "pro_close",
    "hbond_sr_bb",
    "hbond_lr_bb",
    "hbond_bb_sc",
    "hbond_sc",
    "dslf_fa13",
    "rama_prepro",
    "omega",
    "fa_dun",
    "p_aa_pp",
    "yhh_planarity",
    "ref",
]
SCORE_SYNONYMS: dict[str, str] = {
    "fa_atr": "interresidue_attraction",
    "fa_rep": "interresidue_repulsion",
    "fa_sol": "solvation_energy",
    "fa_intra_sol_xover4": "intraresidue_solvation",
    "lk_ball_wtd": "asymmetric_solvation",
    "fa_intra_rep": "intraresidue_repulsion",
    "fa_elec": "electrostatic_potential",
    "pro_close": "proline_ring_closure",
    "hbond_sr_bb": "short_range_backbone_hbond",
    "hbond_lr_bb": "long_range_backbone_hbond",
    "hbond_bb_sc": "backbone_sidechain_hbond",
    "hbond_sc": "sidechain_sidechain_hbond",
    "dslf_fa13": "disulfide_geometry",
    "rama_prepro": "ramachandran_preference",
    "omega": "omega_dihedral_constraint",
    "p_aa_pp": "aa_probability_given_torsion",
    "fa_dun": "sidechain_rotamer_energy",
    "yhh_planarity": "tyrosine_hydroxyl_planarity",
    "ref": "aa_reference_energy",
}
