name: Qwen3 235B Instruct (OpenRouter)
model:
  _target_: agent_rosetta.model.LiteLLMModel
  config:
    model_name: openrouter/qwen/qwen3-235b-a22b-2507

    context_window: 2
    max_query_retries: 1

    reasoning_tag: reasoning
    reasoning_formatting: Write your step-by-step reasoning inside <reasoning></reasoning> tags.
    parse_reasoning: true

    completion_args:
      max_tokens: 4096
      temperature: 0.7