name: Gemini 2.5 Flash (OpenRouter)
model:
  _target_: agent_rosetta.model.LiteLLMModel
  config:
    model_name: openrouter/google/gemini-2.5-flash

    context_window: 2
    max_query_retries: 1

    reasoning_tag: ""
    reasoning_formatting: ""
    parse_reasoning: false

    completion_args:
      max_tokens: 4096
      extra_body:
        reasoning:
          effort: "medium"
