_target_: agent_rosetta.model.LiteLLMModel
config:
  _target_: agent_rosetta.model.LiteLLMModelConfig
  name: Claude Sonnet 4.5 (OpenRouter)
  
  model_name: openrouter/anthropic/claude-sonnet-4.5

  context_window: 2
  max_query_retries: 1

  reasoning_tag: ""
  reasoning_formatting: ""
  parse_reasoning: false

  completion_args:
    max_tokens: 4096
    extra_body:
      reasoning:
        effort: "medium" 