_target_: tasks.rosetta.gfp_stability.GFPStabilityTask
config:
  _target_: tasks.rosetta.task.RosettaTaskConfig
  name: gfp-stability

  prompt: |
    You are given an initial GFP protein (1EMA).

    Your task is to design the sequence such that it will create a 'superfolder' GFP variant with increased melting temperature. The input GFP protein has a Tm of ~75C.
    
    You should leave the CRO residue in position 64 unchanged. Do not delete it, move it, or introduce other CRO residues in the protein sequence.

    The total number of mutations should be small, not exceeding 15, but this will not be enforced during design.

    You will be provided the following proxy metrics to help you assess progess:
    1. Total Rosetta energy.
    2. Cavity volume and radius of gyration.
    3. The RMSD between the Rosetta design and the initial protein structure.

    At each step:
    - The Rosetta environment will execute your action and produce an ensemble of candidate designs.
    - You will be shown summary statistics of the ensemble.
    - You will choose the next action to take, which will be only applied to Pareto optimal candidates in terms of the provided proxy metrics.

  initial_pdb: ${oc.env:AGR_PDB_DIR,./assets/pdbs}/1EMA.pdb

  nstruct: 4
  use_mpi: false
  mpi_mode: local

  guidance_weights:
    aa_composition: 1.0
    atom_pair_constraint: 1.0

  metrics:
    - radius_of_gyration
    - cavity_volume
    - buns
    - res_fa_rep
    - res_rama_prepro

  use_ray: false

  relax_pre_score: true
  relax_movemap_params:
    bb: 0
    chi: 1

  use_ncaas: true
  ncaas:
    - name: GFP chromophore (Thr-Tyr-Gly-derived)
      code3: CRO
      description: GFP chromophore derived from Thr-Tyr-Gly sequence